name: Hassfest Validation

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: "actions/checkout@v3"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
